language: r
sudo: required
dist: trusty

r_packages:
  - covr

before_install:
  - sudo bash install_prerequisite.sh

script:
  - Rscript -e 'devtools::install_github("bowhan/Rncc")'
  - Rscript -e "library(testthat);test_dir('tests');"

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    recipients:
      - bowhan@me.com
    on_success: change
    on_failure: always