# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

NumberConnectedComponents <- function(strs, mmallowed) {
    .Call('_Rncc_NumberConnectedComponents', PACKAGE = 'Rncc', strs, mmallowed)
}

ConnectedComponents <- function(strs, mmallowed) {
    .Call('_Rncc_ConnectedComponents', PACKAGE = 'Rncc', strs, mmallowed)
}

